Fix #93 : TypeError: ctx.dialog.toUpperCase is not a function (#135)
* add: styleClass

* add: styleClass, maxlength

* fix: Type 'undefined' is not assignable to type 'boolean'. (after refactoring to p-button)

* removed unnecessary  'p-button' from styleClass

* fix #93 : TypeError: ctx.dialog.toUpperCase is not a function

* last change reverted: unfortunately gives other error; bug #93 still exists

* fix: maxlength

Co-authored-by: dombidav <40638464+dombidav@users.noreply.github.com>